/*
 * xrick/src/dat_demo.c
 *
 * Demo (attract) mode scripts -- see ../../demo.md
 *
 * GENERATED by `xrick -record`. One entry per submap, indexed by env_submap;
 * { 0, NULL } means "no demo here", which ends the demo and hands the
 * controls back to the keyboard.
 */

#include "system.h"

#ifdef ENABLE_DEMO

#include "demo.h"
#include "control.h"
#include "maps.h"

static demoevt_t demo_evts_01[] = {
  {    60, CONTROL_RIGHT, TRUE  },
  {    82, CONTROL_DOWN , TRUE  },
  {    86, CONTROL_DOWN , FALSE },
  {    88, CONTROL_RIGHT, FALSE },
  {    90, CONTROL_RIGHT, TRUE  },
  {    92, CONTROL_RIGHT, FALSE },
  {   116, CONTROL_RIGHT, TRUE  },
  {   140, CONTROL_RIGHT, FALSE },
  {   140, CONTROL_FIRE , TRUE  },
  {   145, CONTROL_UP   , TRUE  },
  {   148, CONTROL_UP   , FALSE },
  {   150, CONTROL_FIRE , FALSE },
  {   154, CONTROL_RIGHT, TRUE  },
  {   182, CONTROL_UP   , TRUE  },
  {   184, CONTROL_UP   , FALSE },
  {   192, CONTROL_RIGHT, FALSE },
  {   204, CONTROL_UP   , TRUE  },
  {   218, CONTROL_UP   , FALSE },
  {   220, CONTROL_LEFT , TRUE  },
  {   244, CONTROL_LEFT , FALSE },
  {   244, CONTROL_DOWN , TRUE  },
  {   258, CONTROL_DOWN , FALSE },
  {   282, CONTROL_LEFT , TRUE  },
  {   290, CONTROL_LEFT , FALSE },
  {   298, CONTROL_RIGHT, TRUE  },
  {   304, CONTROL_RIGHT, FALSE },
  {   304, CONTROL_FIRE , TRUE  },
  {   306, CONTROL_UP   , TRUE  },
  {   310, CONTROL_UP   , FALSE },
  {   312, CONTROL_FIRE , FALSE },
  {   314, CONTROL_RIGHT, TRUE  },
  {   346, CONTROL_RIGHT, FALSE },
  {   348, CONTROL_DOWN , TRUE  },
  {   358, CONTROL_DOWN , FALSE },
  {   382, CONTROL_LEFT , TRUE  },
  {   394, CONTROL_LEFT , FALSE },
  {   399, CONTROL_FIRE , TRUE  },
  {   403, CONTROL_UP   , TRUE  },
  {   407, CONTROL_UP   , FALSE },
  {   411, CONTROL_FIRE , FALSE },
  {   414, CONTROL_LEFT , TRUE  },
  {   449, CONTROL_LEFT , FALSE },
  {   449, CONTROL_DOWN , TRUE  },
  {   488, CONTROL_DOWN , FALSE },
  {   496, CONTROL_RIGHT, TRUE  },
  {   508, CONTROL_RIGHT, FALSE },
  {   508, CONTROL_LEFT , TRUE  },
  {   538, CONTROL_LEFT , FALSE },
  {   544, CONTROL_LEFT , TRUE  },
  {   560, CONTROL_LEFT , FALSE },
  {   582, CONTROL_RIGHT, TRUE  },
  {   586, CONTROL_UP   , TRUE  },
  {   590, CONTROL_UP   , FALSE },
  {   625, CONTROL_RIGHT, FALSE },
  {   638, CONTROL_LEFT , TRUE  },
  {   668, CONTROL_RIGHT, TRUE  },
  {   668, CONTROL_LEFT , FALSE },
  {   672, CONTROL_RIGHT, FALSE },
  {   672, CONTROL_FIRE , TRUE  },
  {   674, CONTROL_UP   , TRUE  },
  {   676, CONTROL_UP   , FALSE },
  {   678, CONTROL_RIGHT, TRUE  },
  {   678, CONTROL_FIRE , FALSE },
  {   732, CONTROL_UP   , TRUE  },
  {   736, CONTROL_UP   , FALSE },
};

static demoevt_t demo_evts_02[] = {
  {     0, CONTROL_RIGHT, TRUE  },
  {    13, CONTROL_RIGHT, FALSE },
};

demoscript_t demo_scripts[MAP_NBR_SUBMAPS] = {
  /* 0x00 */ { 0, NULL },
  /* 0x01 */ { 65, demo_evts_01 },
  /* 0x02 */ { 2, demo_evts_02 },
  /* 0x03 */ { 0, NULL },
  /* 0x04 */ { 0, NULL },
  /* 0x05 */ { 0, NULL },
  /* 0x06 */ { 0, NULL },
  /* 0x07 */ { 0, NULL },
  /* 0x08 */ { 0, NULL },
  /* 0x09 */ { 0, NULL },
  /* 0x0a */ { 0, NULL },
  /* 0x0b */ { 0, NULL },
  /* 0x0c */ { 0, NULL },
  /* 0x0d */ { 0, NULL },
  /* 0x0e */ { 0, NULL },
  /* 0x0f */ { 0, NULL },
  /* 0x10 */ { 0, NULL },
  /* 0x11 */ { 0, NULL },
  /* 0x12 */ { 0, NULL },
  /* 0x13 */ { 0, NULL },
  /* 0x14 */ { 0, NULL },
  /* 0x15 */ { 0, NULL },
  /* 0x16 */ { 0, NULL },
  /* 0x17 */ { 0, NULL },
  /* 0x18 */ { 0, NULL },
  /* 0x19 */ { 0, NULL },
  /* 0x1a */ { 0, NULL },
  /* 0x1b */ { 0, NULL },
  /* 0x1c */ { 0, NULL },
  /* 0x1d */ { 0, NULL },
  /* 0x1e */ { 0, NULL },
  /* 0x1f */ { 0, NULL },
  /* 0x20 */ { 0, NULL },
  /* 0x21 */ { 0, NULL },
  /* 0x22 */ { 0, NULL },
  /* 0x23 */ { 0, NULL },
  /* 0x24 */ { 0, NULL },
  /* 0x25 */ { 0, NULL },
  /* 0x26 */ { 0, NULL },
  /* 0x27 */ { 0, NULL },
  /* 0x28 */ { 0, NULL },
  /* 0x29 */ { 0, NULL },
  /* 0x2a */ { 0, NULL },
  /* 0x2b */ { 0, NULL },
  /* 0x2c */ { 0, NULL },
  /* 0x2d */ { 0, NULL },
  /* 0x2e */ { 0, NULL },
};

#endif /* ENABLE_DEMO */

/* eof */
