#!/usr/bin/env python3
"""
xrick/src/headless/rd2/joy2script.py -- branch `solver` only, never shipped.

Turns a whole-game RD2 solution (one joystick byte per game_main frame, from map 1's
level start, as xrick2-core -inputs plays it) into src/rd2/dat_rd2_script.c, the
format `xrick -game 2 -record` writes (demo.h; rd2_demo.c): one segment per map,
tick = frames since that map's level start, events = CONTROL_* presses/releases,
each segment starting from no key held (demo_enterSegment clears the mask).

The map boundaries come from replaying the file in xrick2-core -steplog: the frame
whose step leaves the map in the next one ends the segment (PLAN.md T47 phase 9).

usage: joy2script.py <solution.joy> <out.c> [xrick2-core]
"""

import subprocess
import sys

# joystick byte -> CONTROL_* (rd2_demo.c from_joy; control.h)
JOY = [(0x01, 'CONTROL_UP', 0x08), (0x02, 'CONTROL_DOWN', 0x04), (0x04, 'CONTROL_LEFT', 0x02),
       (0x08, 'CONTROL_RIGHT', 0x01), (0x80, 'CONTROL_FIRE', 0x10)]


def segments(joy, core):
    """frames of each map: [(map, [bytes])], from the steplog's map column"""
    r = subprocess.run([core, '-map', '1', '-inputs', joy, '-steplog'],
                       capture_output=True, text=True, check=True)
    data = open(joy, 'rb').read()
    segs, cur, start = [], 1, 0
    for line in r.stdout.splitlines():
        f = line.split()
        if len(f) < 6 or f[1] != 'joy':
            continue
        k, m = int(f[0]), int(f[4])    # frame number (1-based), map after the frame
        if m != cur:
            segs.append((cur, data[start:k]))
            cur, start = m, k
    segs.append((cur, data[start:]))
    return segs


def events(frames):
    ev, prev = [], 0
    for t, b in enumerate(frames):
        for bit, name, _ in JOY:
            if (b ^ prev) & bit:
                ev.append((t, name, bool(b & bit)))
        prev = b
    return ev


def main():
    joy, out = sys.argv[1], sys.argv[2]
    core = sys.argv[3] if len(sys.argv) > 3 else '../build/core2/xrick2-core'
    segs = segments(joy, core)
    by_map = {m: fr for m, fr in segs if 1 <= m <= 4}
    lines = ['/*',
             ' * xrick/src/rd2/dat_rd2_script.c',
             ' *',
             ' * Demo mode scripts -- see ../../include/demo.h',
             ' *',
             ' * GENERATED by src/headless/rd2/joy2script.py (branch solver) from the',
             ' * xrick2-core solution of PLAN.md T47. One entry per map, indexed by map - 1;',
             ' * { 0, NULL } means "no demo here", which ends the demo and hands the',
             ' * controls back to the keyboard.',
             ' */',
             '',
             '#include "system.h"',
             '',
             '#ifdef ENABLE_DEMO',
             '',
             '#include "demo.h"',
             '#include "control.h"',
             '']
    table = []
    for m in range(1, 5):
        fr = by_map.get(m)
        if not fr:
            table.append('  /* 0x%02x */ { 0, NULL },' % (m - 1))
            continue
        ev = events(fr)
        if len(fr) > 0xffff or len(ev) > 0xffff:
            sys.exit('map %d: %d frames, %d events: over the U16 limits of demo.h' % (m, len(fr), len(ev)))
        lines.append('/* map %d: %d frames */' % (m, len(fr)))
        lines.append('static demoevt_t rd2_demo_evts_%02x[] = {' % (m - 1))
        for t, name, down in ev:
            lines.append('  { %5d, %-13s, %-5s },' % (t, name, 'TRUE' if down else 'FALSE'))
        lines.append('};')
        lines.append('')
        table.append('  /* 0x%02x */ { %d, rd2_demo_evts_%02x },' % (m - 1, len(ev), m - 1))
    lines.append('demoscript_t rd2_demo_scripts[4] = {')
    lines += table
    lines += ['};', '', '#endif /* ENABLE_DEMO */', '', '/* eof */', '']
    open(out, 'w', newline='\n').write('\n'.join(lines))
    for m, fr in segs:
        print('map %d: %d frames, %d events' % (m, len(fr), len(events(fr))))


if __name__ == '__main__':
    main()
