#!/bin/bash
# Turns splash.png into splash.png.inc: its bytes as a C initializer list, which
# splash.c #includes. The game loads nothing from disk (the web build has no files to
# load), so the image is compiled in; SDL decodes it at run time (SDL_LoadPNG_IO).
#
#   ./embed.sh            regenerate splash.png.inc (run it after replacing splash.png)
#
# The .inc is generated and checked in, so the builds (Makefile, build.sh, MSBuild)
# need no extra step.

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

{
  echo "/* generated by src/splash/embed.sh from splash.png -- do not edit */"
  od -An -v -tx1 splash.png | sed -e 's/^ *//' -e 's/ *$//' -e '/^$/d' -e 's/\([0-9a-f][0-9a-f]\)/0x\1,/g'
} > splash.png.inc
echo "splash.png.inc: $(wc -c < splash.png) bytes"
