/*
 * xrick/src/rd2/dat_rd2_script.c
 *
 * Demo mode scripts -- see ../../include/demo.h
 *
 * GENERATED by `xrick -record`. One entry per map, indexed by map - 1;
 * { 0, NULL } means "no demo here", which ends the demo and hands the
 * controls back to the keyboard.
 */

#include "system.h"

#ifdef ENABLE_DEMO

#include "demo.h"
#include "control.h"

demoscript_t rd2_demo_scripts[4] = {
  /* 0x00 */ { 0, NULL },
  /* 0x01 */ { 0, NULL },
  /* 0x02 */ { 0, NULL },
  /* 0x03 */ { 0, NULL },
};

#endif /* ENABLE_DEMO */

/* eof */
