/*
 * GENERATED by kb2/gen_rd2_gfx.py -- do not hand-edit.
 *
 * Source: kb2/prg2-ram.bin $18ee6 (main, all 4 maps share one palette) and $18f06 (grey, SPACE-key toggle
 * on the title screen, algo-flow.md S3). 16 words each, ST 3-bit-per-channel 0x0RGB. graphics.md S2.
 */

#include "dat_rd2_palette.h"

const U16 rd2_palette_main[16] = {
  0,0,1568,800,1314,1584,1859,1891,50,337,295,327,
  547,820,1093,1639
};

const U16 rd2_palette_grey[16] = {
  0,0,546,546,546,819,1092,1365,273,546,819,1092,
  546,819,1092,1638
};

/* eof */
