/*
 * GENERATED by tools/extract_sound_engine.py -- do not hand-edit.
 *
 * The Rick Dangerous (Atari ST) sound engine -- code and tables -- lifted verbatim
 * from a Hatari RAM snapshot of the running original game (re/atari_ram_1M.bin). This is the
 * exact 68000 replay code and PSG/sample data from the shipped game, not a
 * re-synthesis. See audio-sndh.md for the design this feeds, and
 * re/assets-manifest.md / re/algo-music.md for the reverse-engineering behind it.
 *
 * Source window: 0x44C10-0x5324F in atari_ram.bin numbering
 * (58944 bytes). Captured from: re/atari_ram_1M.bin, load delta -0x2054 at extraction time --
 * MEMORY.md S6: not a fixed constant, re-run this script if the dump changes.
 *
 * The addresses below are this dump's OWN numbering (canonical + delta), matching
 * where the blob's internal absolute references actually point -- see the P8 note
 * above. syssnd.c uploads the blob at SNDH_ENGINE_BASE and calls the SNDH_FN_* entry
 * points directly; no relocating stub is needed (unlike re/build_sndh.py's SNDH,
 * which needs one only because a generic SNDH player picks its own load address --
 * here we choose it ourselves, so we choose the address that already matches).
 */

#ifndef _DAT_SNDH_ENGINE_H
#define _DAT_SNDH_ENGINE_H

#include "system.h"	/* defines ENABLE_SOUND (via config.h) */

#ifdef ENABLE_SOUND

/* ---- this dump's own address numbering (canonical + -0x2054) -- see the P8 note
   above. Upload() the blob at SNDH_ENGINE_BASE and every SNDH_FN_ and
   SNDH_TRACK_TABLE address is then correct as-is; do NOT "simplify" these back to
   the canonical 0x44C10-numbering constants without also switching the source dump
   to one with delta 0, or every internal absolute reference breaks by the delta. */
#define SNDH_ENGINE_BASE   0x42BBCu   /* reset_sound_chip; Upload() target */
#define SNDH_ENGINE_END    0x511FCu    /* exclusive */
#define SNDH_FN_RESET      0x42BBCu          /* reset_sound_chip() */
#define SNDH_FN_PLAY       0x42C7Au            /* play_music(d0=track, d1=variant) */
#define SNDH_FN_TICK       0x42DB8u            /* music_tick(), call at 50 Hz */
#define SNDH_FN_TIMERA     0x42FB2u          /* setup_timer_a() -- required for PCM */
#define SNDH_FN_SILENCE    0x434D4u         /* silence_all_channels() */
#define SNDH_TRACK_TABLE   0x42EB4u          /* music_track_table[29], 8 bytes/entry */
#define SNDH_N_TRACKS      29

extern const unsigned int sndh_engine_blob_len;
extern const unsigned char sndh_engine_blob[58944];

#endif /* ENABLE_SOUND */

#endif /* _DAT_SNDH_ENGINE_H */

/* eof */
