/*
 * GENERATED by kb2/gen_rd2_gfx.py -- do not hand-edit.
 *
 * Source: kb2/prg2-ram.bin $3ce54, 256 glyphs, 32 bytes each (graphics.md S4a).
 * 8x8, per pixel row 4 plane bytes (no mask, opaque). Glyph n at $3ce54 + 32*n.
 */

#ifndef _DAT_RD2_FONT_H
#define _DAT_RD2_FONT_H

#include "system.h"

#define RD2_FONT_GLYPH_BYTES 32
#define RD2_FONT_GLYPH_COUNT 256

extern const U8 rd2_font[8192];

#endif /* _DAT_RD2_FONT_H */

/* eof */
