/*
 * GENERATED by kb2/gen_rd2_levelimg.py -- do not hand-edit.
 *
 * Source: kb2/assets/maps/map<N>_level.bin, embedded whole (73472 bytes/map).
 * Offset constants below are cited from graphics.md/level-tables.md, not re-derived.
 * Submap counts (per map, derived not stored): {1: 17, 2: 14, 3: 14, 4: 13}
 * Monster-type counts (per map, derived not stored): {1: 49, 2: 43, 3: 50, 4: 68}
 */

#ifndef _DAT_RD2_LEVELIMG_H
#define _DAT_RD2_LEVELIMG_H

#include "system.h"

#define RD2_LEVELIMG_SIZE 73472

#define RD2_LVLIMG_OFF_MONSTERS 0x0	/* monster type table, level-tables.md S4 */
#define RD2_LVLIMG_OFF_SUBMAP_HEADERS 0x1800	/* submap header table, 8 bytes/submap, level-tables.md S1 */
#define RD2_LVLIMG_OFF_SCENES 0x2000	/* cut-scene data, decode_scenes.py */
#define RD2_LVLIMG_OFF_BLOCKMAP 0x3000	/* block maps, graphics.md S3a */
#define RD2_LVLIMG_OFF_BLOCKTABLE 0x3900	/* block table, 16 bytes/block, graphics.md S3a */
#define RD2_LVLIMG_OFF_TILES 0x4900	/* tiles, 256 x 40 bytes, graphics.md S3 */
#define RD2_LVLIMG_OFF_ANIM_TILES 0x7100	/* animated tiles, 32 x 40 bytes, graphics.md S3b */
#define RD2_LVLIMG_OFF_SPRITES 0x7600	/* level sprite bank, 128 x 336 bytes, graphics.md S4 */
#define RD2_LVLIMG_OFF_TILE_ATTR 0x11e00	/* tile attribute table, 256 bytes, level-tables.md/algo-actors.md S6 */

extern const U8 rd2_levelimg_map1[RD2_LEVELIMG_SIZE];
extern const U8 rd2_levelimg_map2[RD2_LEVELIMG_SIZE];
extern const U8 rd2_levelimg_map3[RD2_LEVELIMG_SIZE];
extern const U8 rd2_levelimg_map4[RD2_LEVELIMG_SIZE];
extern const U8 rd2_stage1_map1[34816];
extern const U8 rd2_stage1_map2[37888];
extern const U8 rd2_stage1_map3[37376];
extern const U8 rd2_stage1_map4[39936];
extern const U8 * const rd2_stage1[4];
extern const U32 rd2_stage1_size[4];

extern const U8 * const rd2_levelimg[4]; /* index 0..3 = map 1..4 */

#endif /* _DAT_RD2_LEVELIMG_H */

/* eof */
