/*
 * GENERATED by kb2/gen_rd2_program.py -- do not hand-edit.
 *
 * Source: kb2/assets/RICK2.PRG data section, hnk.depack()ed (LSD! layer): 194332 bytes, md5 c834cae68ffe462fdd4cd9ccffad3b13.
 * Load address: RAM = offset + $f8b8 (so this blob spans $f8b8..$3efd4).
 * Pristine program, NOT the prg2-ram.bin snapshot (kb2/sound-ref.md §9).
 */

#ifndef _DAT_RD2_PROGRAM_H
#define _DAT_RD2_PROGRAM_H

#include "system.h"

#define RD2_PROG_BASE 0xf8b8u
#define RD2_PROG_SIZE 194332

extern const U8 rd2_program[RD2_PROG_SIZE];

#endif /* _DAT_RD2_PROGRAM_H */

/* eof */
