/*
 * GENERATED by kb2/gen_rd2_gfx.py -- do not hand-edit.
 *
 * Source: kb2/prg2-ram.bin $35a74, four 0x600-byte banners (graphics.md S4b, FUN_000194ce args 0-3).
 * 256x24 px, planes 0-1 only (4 bytes/16px group/scanline: word plane0, word plane1), 24 scanlines.
 * 0=CONGRATULATIONS!, 1=HALL OF FAME, 2=SELECT LEVEL, 3=LOADING... (arg 3 also draws 80px lower).
 */

#ifndef _DAT_RD2_BANNERS_H
#define _DAT_RD2_BANNERS_H

#include "system.h"

#define RD2_BANNER_BYTES 1536
#define RD2_BANNER_COUNT 4

extern const U8 rd2_banner_congratulations[1536]; /* arg 0 */
extern const U8 rd2_banner_hall_of_fame[1536]; /* arg 1 */
extern const U8 rd2_banner_select_level[1536]; /* arg 2 */
extern const U8 rd2_banner_loading[1536]; /* arg 3 */

extern const U8 * const rd2_banners[RD2_BANNER_COUNT]; /* index by FUN_000194ce's arg */

#endif /* _DAT_RD2_BANNERS_H */

/* eof */
