/*
 * GENERATED by kb2/gen_rd2_gfx.py -- do not hand-edit.
 *
 * Source: kb2/prg2-ram.bin $18ee6 (main, all 4 maps share one palette) and $18f06 (grey, SPACE-key toggle
 * on the title screen, algo-flow.md S3). 16 words each, ST 3-bit-per-channel 0x0RGB. graphics.md S2.
 */

#ifndef _DAT_RD2_PALETTE_H
#define _DAT_RD2_PALETTE_H

#include "system.h"

#define RD2_PALETTE_COLORS 16

extern const U16 rd2_palette_main[16];
extern const U16 rd2_palette_grey[16];

#endif /* _DAT_RD2_PALETTE_H */

/* eof */
