/*
 * GENERATED by kb2/gen_rd2_demo.py -- do not hand-edit.
 *
 * Sources: kb2/assets/maps/map<N>_demo.bin for maps 1/2/4 (genuine depacked HNK streams).
 * Map 3: disks/RICKDA2/RD2[7680:8704] -- the T25 candidate, NOT the genuine (corrupted) HNK.
 * *** Map 3's stream is UNVERIFIED against an original disk (no reference copy exists). ***
 * *** It is a reconstruction the user chose to ship anyway (port-rd2.md S4, 2026-09-22); ***
 * *** PLAN.md T25/T36 track this. Do not present it as a proven-original byte sequence. ***
 */

#ifndef _DAT_RD2_DEMO_H
#define _DAT_RD2_DEMO_H

#include "system.h"

#define RD2_DEMO_BYTES 1024
#define RD2_DEMO_MAP3_IS_RECONSTRUCTED 1

extern const U8 rd2_demo_map1[RD2_DEMO_BYTES];
extern const U8 rd2_demo_map2[RD2_DEMO_BYTES];
extern const U8 rd2_demo_map3[RD2_DEMO_BYTES];
extern const U8 rd2_demo_map4[RD2_DEMO_BYTES];

extern const U8 * const rd2_demo[4]; /* index 0..3 = map 1..4; map 3 (index 2) is reconstructed, see above */

#endif /* _DAT_RD2_DEMO_H */

/* eof */
