/*
 * GENERATED by kb2/gen_rd2_scripts_inprogram.py -- do not hand-edit.
 *
 * Source: kb2/prg2-ram.bin[0x12e5e:0x15b38] (11482 bytes), the span reached by every
 * documented in-program script entry point and every jump target from them --
 * computed mechanically, see this script's docstring. Entry-point offsets below
 * are relative to this blob's own base (0x12e5e).
 */

#ifndef _DAT_RD2_SCRIPTS_INPROGRAM_H
#define _DAT_RD2_SCRIPTS_INPROGRAM_H

#include "system.h"

#define RD2_INPROGRAM_SCRIPTS_SIZE 11482
#define RD2_INPROGRAM_SCRIPTS_BASE 0x12e5e

#define RD2_SCRIPT_PICKUP_A 0x1810	/* absolute $1466e */
#define RD2_SCRIPT_PICKUP_B 0x182c	/* absolute $1468a */
#define RD2_SCRIPT_PICKUP_C 0x1838	/* absolute $14696 */
#define RD2_SCRIPT_UNKNOWN_12ed6 0x78	/* absolute $12ed6 */
#define RD2_SCRIPT_BOMB 0x0	/* absolute $12e5e */
#define RD2_SCRIPT_GROUP_ANIM_0 0x2b98	/* absolute $159f6 */
#define RD2_SCRIPT_GROUP_ANIM_1 0x2b9e	/* absolute $159fc */
#define RD2_SCRIPT_GROUP_ANIM_2 0x2ba4	/* absolute $15a02 */
#define RD2_SCRIPT_GROUP_ANIM_3 0x2bc0	/* absolute $15a1e */
#define RD2_SCRIPT_GROUP_ANIM_4 0x2bc6	/* absolute $15a24 */
#define RD2_SCRIPT_GROUP_ANIM_5 0x2bf6	/* absolute $15a54 */
#define RD2_SCRIPT_GROUP_ANIM_6 0x2bfc	/* absolute $15a5a */
#define RD2_SCRIPT_GROUP_ANIM_7 0x2bfe	/* absolute $15a5c */
#define RD2_SCRIPT_GROUP_ANIM_8 0x2c00	/* absolute $15a5e */
#define RD2_SCRIPT_GROUP_ANIM_9 0x2c10	/* absolute $15a6e */
#define RD2_SCRIPT_GROUP_MOVE_0 0x2a4c	/* absolute $158aa */
#define RD2_SCRIPT_GROUP_MOVE_1 0x2c16	/* absolute $15a74 */
#define RD2_SCRIPT_GROUP_MOVE_2 0x2c3a	/* absolute $15a98 */
#define RD2_SCRIPT_GROUP_MOVE_3 0x2c66	/* absolute $15ac4 */
#define RD2_SCRIPT_GROUP_MOVE_4 0x2c92	/* absolute $15af0 */
#define RD2_SCRIPT_GROUP_MOVE_5 0x2cbe	/* absolute $15b1c */

extern const U8 rd2_inprogram_scripts[RD2_INPROGRAM_SCRIPTS_SIZE];

#endif /* _DAT_RD2_SCRIPTS_INPROGRAM_H */

/* eof */
