/*
 * GENERATED by kb2/gen_rd2_gfx.py -- do not hand-edit.
 *
 * Sources (graphics.md S4): shared banks A/C from kb2/prg2-ram.bin ($37274, $3a844; RAM only,
 * not in any .HNK, present after RICK2.PRG unpacks itself -- see PLAN.md T39, not needed for extraction).
 * 336 bytes/frame, 32x21 px: per pixel row, 4 longwords = plane0..plane3 (32 px, MSB=left px). No stored
 * mask -- colour 0 (all 4 planes 0) is transparent; the port's blitter (P4) implements this at draw time.
 * Frame-id -> bank routing (id = actor record +0xe, id mod 64 indexes within the bank): 0-63 -> shared A
 * (only 0-40 valid), 64-127 -> per-map level bank (dat_rd2_levelimg.c), 128-191 -> shared C (only
 * 128-156 valid), 192-255 -> per-map level bank + 0x7600 (id 0xfe draws nothing). graphics.md S4.
 */

#ifndef _DAT_RD2_SPRITES_H
#define _DAT_RD2_SPRITES_H

#include "system.h"

#define RD2_SPRITE_BYTES 336
#define RD2_SPRITE_SHARED_A_COUNT 41
#define RD2_SPRITE_SHARED_C_COUNT 29

extern const U8 rd2_sprites_shared_a[13776];
extern const U8 rd2_sprites_shared_c[9744];

#endif /* _DAT_RD2_SPRITES_H */

/* eof */
