/*
 * GENERATED by kb2/gen_rd2_sound.py -- do not hand-edit.
 *
 * Source: kb2/prg2-ram.bin[0x19e96:0x31eb0] (98330 bytes), sound-ref.md S1/S5.
 * Verbatim, unpatched -- see this script's docstring for the one required
 * runtime patch (P5's job, not baked in here) and the entry-point addresses.
 */

#ifndef _DAT_RD2_SNDH_ENGINE_H
#define _DAT_RD2_SNDH_ENGINE_H

#include "system.h"

#define RD2_SNDH_BASE 0x19e96u
#define RD2_SNDH_SIZE 98330
#define RD2_SNDH_FN_DISPATCH 0x1a6aau	/* D0=id 0-91, D1=param */
#define RD2_SNDH_FN_TICK 0x1a866u	/* call once per 50 Hz VBL */
#define RD2_SNDH_FN_TIMERA_INSTALL 0x1a978u	/* call once at init */
#define RD2_SNDH_STATE_MASTER 0x1a974u	/* byte; clear to 0 before each dispatch */
#define RD2_SNDH_DISPATCH_TABLE 0x1c376u	/* 92 x 8 bytes, ids 0-91 */
#define RD2_SNDH_DISPATCH_ENTRIES 92
#define RD2_SNDH_DEMOFLAG_SITE_1 0x1a70cu	/* 4-byte operand, currently points at 0x3efb6 (outside blob) */
#define RD2_SNDH_DEMOFLAG_SITE_2 0x1a7fcu
#define RD2_SNDH_DEMOFLAG_ORIGINAL_TARGET 0x3efb6u

extern const U8 rd2_sndh_engine_blob[RD2_SNDH_SIZE];

#endif /* _DAT_RD2_SNDH_ENGINE_H */

/* eof */
