#!/bin/bash
# Turns each .glsl under src/shaders/ into a .glsl.inc next to it: the same text as one
# C string literal, which sysvid_gl.c #includes. The game loads nothing from disk (the web
# build has no files to load), so shader sources are compiled in like the other data.
#
#   ./embed.sh            regenerate every .glsl.inc (run it after adding or editing a .glsl)
#
# The .glsl files are libretro glsl-shaders sources, kept verbatim; the .glsl.inc files are
# generated and checked in, so the builds (Makefile, build.sh, MSBuild) need no extra step.
# MSVC caps one string literal at 16380 bytes and a concatenation of literals at 65535, so
# the text is one literal per line and a source must stay under 64 KiB.

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

find . -name '*.glsl' | sort | while read -r f; do
  size=$(tr -d '\r' < "$f" | wc -c)
  if [ "$size" -ge 65535 ]; then
    echo "error: $f is $size bytes, over MSVC's 65535-byte string limit" >&2
    exit 1
  fi
  {
    echo "/* generated by src/shaders/embed.sh from $(basename "$f") -- do not edit */"
    tr -d '\r' < "$f" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/"/' -e 's/$/\\n"/'
  } > "$f.inc"
  echo "$f.inc"
done
